# frozen_string_literal: true

source "http://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
repo_name = "knaway"

gem 'capybara', '3.1.0'
gem 'cucumber'
gem 'rspec'
gem 'rubyzip', '1.2.1'
gem 'selenium-webdriver'
